### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by Mihai-P** [udokmeci/yii2-kont-trevor#2]
Your extension also needs font awesome for showing icons. But it does not require a font-awesome asset or anything similar. Can you add to the assets and to the requirement what you use to make it work properly.

**Comment by udokmeci** [comment]
Fixed with dependecy  https://github.com/udokmeci/yii2-kont-trevor/commit/1596368493960be4cb3d2ea7fb4b7fa38a93b0d7
