### ISSUE TITLE
Need Input to Start

### ISSUE THREAD

**Issue by nishadotcom** [udokmeci/yii2-kont-trevor#4]
@udokmeci 

I like to use the yii2-kont-trevor extension. I have installed the extension. I could not get the view as you have showed https://camo.githubusercontent.com/cd1d4b41ac1832d2eaecd912c457c503a487f8d1/68747470733a2f2f7261772e6769746875622e636f6d2f75646f6b6d6563692f796969322d6b6f6e742d747265766f722f6d61737465722f6b6f6e742d747265766f722e676966

Please let me know what I am missing.

Best
nishadotcom

**Comment by udokmeci** [comment]
Thank you for interest,

Is there any particular error on composer, console or php, anything that may lead to suggestion?

**Comment by nishadotcom** [comment]
No, I did not get any errors @udokmeci .

I shall attach my code & screens for your better understanding of my issue.

config/web.php -> in components []
`'kontTrevor' => [
            'class' => 'udokmeci\yii2kt\KontTrevor',
            'on init'=> function($e){
                $e->sender->addProviders(require_once Yii::getAlias('@vendor/udokmeci/yii2-kont-trevor/src/udokmeci/yii2kt/config/base-blocks.php'));
            }
        ],`
views/contact.php
`<?= $form->field($model, 'body')->widget(\kato\sirtrevorjs\SirTrevor::classname(),[
        'debug'=>true,
        'imageUploadUrl'=>'',//Url::to(['/site/st-upload']),
        'blockTypes' => [ 'Imagetop','Imageleft', "Redactor", "Headex", 'Twocolumns', 'Threecolumns','Imageright','Textblock','Hr'],
        //'blockTypes'=>['Redactor']
  ]); ?>`

Please see my screens. I attach them one by one,
**1st Screen**
![1](https://cloud.githubusercontent.com/assets/15242739/16105102/ed052d66-33a4-11e6-8b0f-61a372996303.png)

**2nd Screen**
![2](https://cloud.githubusercontent.com/assets/15242739/16105122/0e12c1f8-33a5-11e6-8d1e-12b6a54a54bc.png)

**3rd Screen**
![3](https://cloud.githubusercontent.com/assets/15242739/16105126/1fe99f14-33a5-11e6-9a17-12f44e2435ed.png)

Best,
nishadotcom

**Comment by udokmeci** [comment]
Seems like js error I ll investigate.

**Comment by nishadotcom** [comment]
Ok @udokmeci

**Comment by udokmeci** [comment]
Hi, 
It works for me, is there any change you forget to register assets? on that line 
https://github.com/udokmeci/yii2-kont-trevor/blame/master/README.md#L49

Hope that works, if so probably I need to create another widget for that maybe you can do it and send PR?

**Comment by nishadotcom** [comment]
I did not add the below line to my code

<?php \udokmeci\yii2kt\assets\CustomSirTrevorAsset::register($this); ?>

**Comment by nishadotcom** [comment]
Is there any url to see???
can we see demo????

**Comment by udokmeci** [comment]
Just register the asset on the view you like to render the widget. As you can see it is not a library native widget, It is extending the functionality of widget of another library.
